name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.x'
        
    - name: Build
      run: |
        xcodebuild build -scheme "todo-app" -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        
    - name: Run tests
      run: |
        xcodebuild test -scheme "todo-app" -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        
    - name: Validation Success
      if: success()
      run: |
        echo "Build validation completed successfully."