name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
        # Make sure we're using the package.swift and not getting confused with Xcode project
        swift package resolve
        swift build -v
        
    - name: Run tests
      run: swift test -v
